# Generated by Django 2.2 on 2019-05-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='group',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='generated_person',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
