# Generated by Django 2.2 on 2019-05-25 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_auto_20190525_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='index',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
