# Generated by Django 2.2 on 2019-05-26 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_auto_20190526_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('meal_type', models.IntegerField(choices=[(1, 'breakfast'), (2, 'lunch'), (3, 'dinner'), (4, 'snacks')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('recipe_type', models.CharField(max_length=30)),
                ('generated_time', models.DateTimeField(auto_now_add=True)),
                ('generated_person', models.CharField(blank=True, max_length=30)),
                ('operation', models.TextField(blank=True, max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_weight', models.DecimalField(decimal_places=1, max_digits=4)),
                ('element_type', models.IntegerField(choices=[(1, 'main'), (2, 'flavour')], null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Food')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Recipe')),
            ],
        ),
        migrations.AlterField(
            model_name='assessment',
            name='foods',
            field=models.ManyToManyField(through='lab.AssessmentUse', to='lab.Food'),
        ),
        migrations.DeleteModel(
            name='FoodUse',
        ),
        migrations.AddField(
            model_name='recipe',
            name='foods',
            field=models.ManyToManyField(through='lab.RecipeUse', to='lab.Food'),
        ),
        migrations.AddField(
            model_name='assessmentuse',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Assessment'),
        ),
        migrations.AddField(
            model_name='assessmentuse',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.Food'),
        ),
    ]
