# Generated by Django 2.2 on 2019-05-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0005_auto_20190526_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='carbohydate',
            new_name='carbohydrate',
        ),
    ]
